kind: Deployment
apiVersion: apps/v1
metadata:
  name: smtp
  namespace: postal
spec:
  selector:
    matchLabels:
      process_type: smtp
  replicas: 1
  template:
    metadata:
      labels:
        process_type: smtp
    spec:
      containers:
        - name: smtp
          image: ghcr.io/postalserver/postal
          imagePullPolicy: Always
          command:
            - bundle
            - exec
            - rake
            - postal:smtp_server
          ports:
            - containerPort: 2525
          livenessProbe:
            tcpSocket:
              port: 2525
            periodSeconds: 15
            initialDelaySeconds: 5
          readinessProbe:
            tcpSocket:
              port: 2525
            periodSeconds: 15
            initialDelaySeconds: 5
          volumeMounts:
          - mountPath: /config
            name: postal-config
      volumes:
      - name: postal-config
        persistentVolumeClaim:
          claimName: postal-config-pvc
