kind: Deployment
apiVersion: apps/v1
metadata:
  name: worker
  namespace: postal
spec:
  selector:
    matchLabels:
      process_type: worker
  replicas: 1
  template:
    metadata:
      labels:
        process_type: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/postalserver/postal
          imagePullPolicy: Always
          command:
            - bundle
            - exec
            - ruby
            - script/worker.rb
          volumeMounts:
          - mountPath: /config
            name: postal-config
      volumes:
      - name: postal-config
        persistentVolumeClaim:
          claimName: postal-config-pvc