kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
  namespace: postal
spec:
  selector:
    matchLabels:
      process_type: web
  replicas: 1
  template:
    metadata:
      labels:
        process_type: web
    spec:
      containers:
        - name: puma
          image: ghcr.io/postalserver/postal
          imagePullPolicy: Always
          command:
            - bundle
            - exec
            - puma
            - -C
            - config/puma.rb
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /login
              port: 5000
              httpHeaders:
                - name: Host
                  value: ${MX.FQDN}
            periodSeconds: 3
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /login
              port: 5000
              httpHeaders:
                - name: Host
                  value: ${MX.FQDN}
            periodSeconds: 3
            initialDelaySeconds: 10
          volumeMounts:
          - mountPath: /config
            name: postal-config
      volumes:
      - name: postal-config
        persistentVolumeClaim:
          claimName: postal-config-pvc