apiVersion: v1
kind: PersistentVolume
metadata:
  name: postal-config-pv
  namespace: postal
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100M
  nfs:
    path: ${PATH/TO/SHARE}
    server: ${IP_TO_NFS_SERVER}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: postal-config-pvc
  namespace: postal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  storageClassName: ""
  volumeMode: Filesystem