apiVersion: v1
kind: Service
metadata:
  name: smtp-svc
  namespace: postal
spec:
  ports:
  - nodePort: 32025
    port: 2525
    protocol: TCP
    targetPort: 2525
  selector:
    process_type: smtp
  type: NodePort